/**
 * `data/vessel/info.yaml` — the frontend's copy of the vessel configuration.
 *
 * The plugin config page is the source of truth; this file is an output,
 * rewritten whenever the config changes. One key is not ours: `passage:`.
 * The passage banner is edited from the GitHub web UI by whoever is ashore
 * following the boat, so it is read back off the published file and carried
 * through untouched. Moving it into plugin config would mean editing over the
 * VPN instead of from a phone, which is a step backwards.
 */
import yaml from 'js-yaml';
import type { PluginConfig } from './config';

export interface VesselIdentity {
  name: string;
  mmsi: string;
  signalk?: { host?: string; port?: string | number; protocol?: string };
}

const HEADER = `# Generated by the signalk-github-pages plugin — edits here are overwritten.
# Change these values on the plugin's configuration page in the Signal K admin UI.
#
# The one exception is the 'passage:' block below, which the plugin preserves.
# Set it from the GitHub web UI before departure to show voyage context on the
# tracker, and delete it on arrival:
#
# passage:
#   from: "San Francisco, CA"
#   to: "Santa Cruz, CA"
#   departed: "2026-02-20"
`;

/** Lift the user-owned `passage:` block out of the published file. */
export function extractPassage(existingYaml: string | null | undefined): unknown {
  if (!existingYaml) return undefined;
  try {
    const parsed = yaml.load(existingYaml);
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
      const passage = (parsed as Record<string, unknown>).passage;
      if (passage && typeof passage === 'object') return passage;
    }
  } catch {
    // A file we cannot parse has no passage worth keeping; the rewrite below
    // replaces it with something valid.
  }
  return undefined;
}

/**
 * Parse the free-form extras block.
 *
 * Invalid YAML is reported and skipped: a typo in an optional field must not
 * stop the boat publishing its position.
 */
export function parseExtraFields(
  extraYaml: string,
  onProblem: (message: string) => void = () => {},
): Record<string, unknown> {
  if (!extraYaml.trim()) return {};
  let parsed: unknown;
  try {
    parsed = yaml.load(extraYaml);
  } catch (error: any) {
    onProblem(`Extra site fields are not valid YAML and were skipped: ${error?.message ?? error}`);
    return {};
  }
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    onProblem('Extra site fields must be a YAML mapping (key: value); they were skipped.');
    return {};
  }
  const fields = parsed as Record<string, unknown>;
  if ('passage' in fields) {
    // passage is read back off the published file every rewrite, so a copy
    // here would fight with the one edited on GitHub.
    onProblem('Extra site fields must not set "passage:" — edit it in the repository instead. Ignoring it.');
    delete fields.passage;
  }
  return fields;
}

export function renderVesselInfo(
  config: PluginConfig,
  identity: VesselIdentity,
  existingYaml?: string | null,
  onProblem: (message: string) => void = () => {},
): string {
  const passage = extractPassage(existingYaml);
  const document: Record<string, unknown> = {};

  if (passage !== undefined) document.passage = passage;
  document.theme = config.site.theme;
  if (identity.name) document.name = identity.name;
  if (identity.mmsi) document.mmsi = identity.mmsi;
  if (config.site.marinetrafficShipId)
    document.marinetraffic_ship_id = config.site.marinetrafficShipId;
  if (config.site.postgsailLogsUrl) document.postgsail_logs_url = config.site.postgsailLogsUrl;
  if (config.site.uscgNumber) document.uscg_number = config.site.uscgNumber;
  if (config.site.hullNumber) document.hull_number = config.site.hullNumber;
  if (identity.signalk?.host) {
    document.signalk = {
      host: identity.signalk.host,
      port: String(identity.signalk.port ?? 3000),
      protocol: identity.signalk.protocol ?? 'http',
    };
  }
  if (config.timezone) document.timezone = config.timezone;
  document.privacy_zones = config.privacyZones.map((zone) => ({
    name: zone.name || 'Privacy zone',
    lat: zone.lat,
    lon: zone.lon,
    radius_m: zone.radius_m,
  }));

  // Extras are applied last and win, which is what makes them an escape
  // hatch rather than decoration. Every override is named in the log, so a
  // field that stopped tracking the config page is visible rather than
  // mysterious.
  for (const [key, value] of Object.entries(parseExtraFields(config.site.extraYaml, onProblem))) {
    if (key in document && document[key] !== value) {
      onProblem(`Extra site field "${key}" overrides the value from the plugin config.`);
    }
    document[key] = value;
  }

  return `${HEADER}\n${yaml.dump(document, { lineWidth: 100, noRefs: true })}`;
}
